### ISSUE TITLE
euphony-speaker README.md 채우기

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony-speaker#4]
@euphony-io/euphony-b 팀에 배정드리는 첫번째 이슈입니다.

https://github.com/pytorch/android-demo-app/tree/master/ASLRecognition
https://github.com/pytorch/android-demo-app/tree/master/TorchVideo

위 보시면 다양한 데모 앱에 대하여 README.md가 업데이트 되어 있어요.
여러분이 공식 euphony-speaker 앱의 README.md가 현재 부재하니 업데이트 해보면 좋을 것 같아요.

한국어/영어 버전 각각 만들어주시면 좋을 것 같고 영어를 기본 컨텐츠로 잡으면 좋을 것 같습니다.

우선은 여기 issue 페이지를 통해서 커뮤니케이션을 하면서 전체 구성을 완성해보시구요.
내용도 어떻게 쓸지 각자 커뮤니케이션을 여기서 남겨가면서 작성해보면 좋겠습니다.

PR은 이번주 토요일 이후에 진행해보시도록 할게요 :)

**Comment by JuSeongPil** [comment]
멘토님 실례지만 제가 실수로 Assignees에서 remove를 해서 다시 초대를 부탁드려도 될까요?

**Comment by jopopcorn** [comment]
회의를 통해 euphony-speaker의 전체 구성을 다음와 같이 정리해보았습니다.

역할 | 구성 |
-- | :--: | 
성필 | 프로젝트 소개글 | 
수연 | 최소 안드로이드 버전 명시 | 
도현 | 데모 앱 이미지 추가 |  
수연 | License |  
도현 | 영상 링크 첨부 | 
수진 | 데모 앱 사용법 | 

각자 맡은 부분을 영어로 적어본 후 고칠 부분이 있다면 함께 수정해보면 좋을 것 같아요!

**Comment by jopopcorn** [comment]
@euphony-io/coophony 
안드로이드 버전 명시에 관해 다음과 같이 이슈 남기려 하는데 괜찮을까요?

> This project does not specify a minimum version of Android. Is the library also available in Android 7.0 (API level 24)? Please specify the minimum version in README.
> 
> 이 프로젝트에는 안드로이드 최소 버전이 명시되어 있지 않습니다. 안드로이드 API 24 버전에서도 라이브러리 사용이 가능합니까? README에 최소 버전을 명시해주었으면 좋겠습니다.

**Comment by designe** [comment]
> @euphony-io/coophony
> 안드로이드 버전 명시에 관해 다음과 같이 이슈 남기려 하는데 괜찮을까요?
> 
> > This project does not specify a minimum version of Android. Is the library also available in Android 7.0 (API level 24)? Please specify the minimum version in README.
> > 이 프로젝트에는 안드로이드 최소 버전이 명시되어 있지 않습니다. 안드로이드 API 24 버전에서도 라이브러리 사용이 가능합니까? README에 최소 버전을 명시해주었으면 좋겠습니다.

네 좋아요!!

**Comment by designe** [comment]
@sujin9 
#### Live mode
말씀하신대로 현재 데모버전에는 UI로만 표현되어 있는데 define만 되어 있고 해당 Switch를 현재 사용하고 있지 않습니다.
live-mode는 짧은 단위로 데이터를 보내고 인식하는 기능인데 아직 라이브러리서도 구현이 완성되지 않은 기능인데 여기 UI로만 남아있네요!

- 0.7.1.6 버전에서는 쓰이지 않을 예정이기 때문에 해당 UI Component 제거가 필요해보입니다.
https://github.com/euphony-io/euphony-speaker/blob/39d6641914d13dd3c1dd643c4afac6e7a001a7f8/app/src/main/java/co/jbear/euphony_speaker/MainActivity.java#L20

@sujin9 님이 제거해주고, 해당 내용 Pull Request로 날려주세요 :)


#### Spinner의 숫자들
https://github.com/euphony-io/euphony-speaker/blob/39d6641914d13dd3c1dd643c4afac6e7a001a7f8/app/src/main/java/co/jbear/euphony_speaker/MainActivity.java#L63

Spinner의 숫자들로 설정된 count는 위 라인의 process 함수에 사용됩니다. 추측하신 것처럼 음파의 전송횟수 맞습니다!

**Comment by sujin9** [comment]
@designe 
답변 감사합니다 !! :)

@euphony-io/coophony 
### Remove UI component that is not implemented
- Remove 'Live mode' UI component because it won't be used in 0.7.1.6 version. 

PR 메시지는 이렇게 쓰면 괜찮을까요??

**Comment by aiclaudev** [comment]
@euphony-io/coophony 

대략적인 speaker 데모 앱 사용법 영상을 제작하였습니다. 해석과 추가할 점, 개선할 점 등을 피드백해주시면 감사하겠습니다! 

<https://youtu.be/W8NIl4W-FTI>

**Comment by jopopcorn** [comment]
@aiclaudev 다운받는 법부터 사용법까지 아주 상세하게 올려주셨네요 특별히 고칠 점도 없어 보입니다! 잘하셨네요! 👍

**Comment by jopopcorn** [comment]
리드미 구성을 생각해 보았는데 아래처럼 배치하면 괜찮을까요? 자유롭게 의견 남겨주세요~



# Euphony-Speaker
[데모 앱 이미지 첨부]
어떤 데모 앱인지 간단한 소개글을 작성하는 공간

</br>

# Directions
[코드 불러오기부터 실행까지의 과정을 영상으로 보여주는 링크 첨부] + 이 링크에 대한 설명 작성
데모 앱 사용법을 작성하는 공간

</br>

# Compatibility
Euphony의 안드로이드 최소 버전을 명시하는 공간

</br>

# License
라이센스를 명시하는 공간

</br>

# Report Issues
이슈가 있다면 알려달라는 문구를 적는 공간

**Comment by aiclaudev** [comment]
구성이 너무 깔끔하고 좋습니다!! 특히 멘토님께서 보내주신 예시 README.md엔 **Report Issue** 부분이 없었는데, 아이디어가 정말 좋으신 것 같습니다. ㅎㅎ
추가로, **'Euphony-listener와 speaker를 같이 테스트하는 것을 추천하고, 음파통신을 경험해보세요. '** 등의 문구를 넣으면 README를 읽는 사람들이 더욱 흥미롭게 테스트를 할 수 있지 않을까 하는 생각을 합니다!

**Comment by sujin9** [comment]
영상 깔끔하고 설명도 자세하고 좋아요 !! :) 
리드미도 깔끔하고, 도현님께서 말씀하신 문구 넣는것도 좋은 아이디어 같습니다!!! ㅎㅎ
추후에는 함께 실제 단말기 두대로 listener-speaker 통신하는 모습을 촬영한 영상도 함께 올리면 
다른 사람들에게도 더 흥미가 생기지 않을까 하는 생각도 들어요!

**Comment by jopopcorn** [comment]
두 분 말씀대로 문구도 추가하고 단말기 두대가 함께 통신하는 모습을 영상으로 올리면 좋을 것 같아요!
2주차 계획 중에 샘플 앱 만들기가 있어서 저희끼리 샘플 앱을 만들고 나서 추후에 영상을 추가해도 좋을 것 같습니다!

**Comment by jopopcorn** [comment]
## Compatibility
**Minimum Android SDK**: Euphony requires at least Android API 14.


</br>

## License
Euphony is licensed under the Apache 2.0 license. See the [LICENSE](https://github.com/euphony-io/euphony-speaker/blob/master/LICENSE) file for details.

</br>

## Report Issues
To report a specific problem or feature request, [please open a new issue.](https://github.com/euphony-io/euphony-speaker/issues/new)

</br>


담당 파트 번역해서 올립니다!

**Comment by sujin9** [comment]
사용 설명에 관한 부분입니다! 

## Directions
---
### 1. Open Android Studio
Clone the project and open it with Android Studio.

### 2. Run the app
Select an Android emulator or device and run the app.
(screenshot - 추가예정)
You can enter the text you want to transmit. You can also select the number of transmissions in the spinner. 
You can send or stop sending text via the button at the bottom.

> Recommendation! You can try it with [Euphony-Listener demo app](https://github.com/euphony-io/euphony-listener).

A guidance screencast is available [here](https://youtu.be/W8NIl4W-FTI).

**Comment by JuSeongPil** [comment]
Euphony-Speaker

Euphony Speaker demo app that generates noiseless sound wave data using frequencies in the inaudible band to communicate with other devices.
(비가청대역의 주파수를 사용하여 무소음의 음파 데이터를 생성해 다른 디바이스와 통신할 수 있도록 하는 Euphony Speaker 데모 앱입니다.)

**Comment by sujin9** [comment]
# Euphony-Speaker
![euphony_logo](https://user-images.githubusercontent.com/8490058/129358383-14b6f34d-9264-4c49-9538-3ef2e62a6490.png)
Acoustic Data Telecommunication Library. This is for Android version.
Euphony provides a handiness library designed to communicate with other devices(android and web) using mic and recorder.

Official Facebook Page : https://www.facebook.com/euphonyproject
Official Library Site : https://dev.jbear.co/euphony

Euphony Speaker demo app that generates noiseless sound wave data using frequencies in the inaudible band to communicate with other devices.

## Directions
#### 1. Open Android Studio
Clone the project and open it with Android Studio.

#### 2. Run the app
Select an Android emulator or device and run the app.
![screenshot](https://user-images.githubusercontent.com/8490058/129358218-e53e4edd-dfe4-4930-bf82-1ed61bdc5b6b.jpg)

You can enter the text you want to transmit. You can also select the number of transmissions in the spinner.
You can send or stop sending text via the button at the bottom.

A guidance screencast is available [here](https://www.youtube.com/watch?v=W8NIl4W-FTI&feature=youtu.be).

💡 Recommendation! You can try it with [Euphony-Listener demo app](https://github.com/euphony-io/euphony-listener).

## Compatibility
Minimum Android SDK: Euphony requires at least Android API 14.

## License
Euphony is licensed under the Apache 2.0 license. See the [LICENSE](https://github.com/euphony-io/euphony-speaker/blob/master/LICENSE) file for details.

## Report Issues
To report a specific problem or feature request, [please open a new issue](https://github.com/euphony-io/euphony-speaker/issues/new).


우선 내용들 합해서 써봤는데 수정할 내용이 있거나 잘못된 부분이 있으시면 말씀해주세요!!!

**Comment by jopopcorn** [comment]
@euphony-io/coophony
Our Mentor gave us [feedback](https://github.com/euphony-io/euphony-speaker/pull/6#pullrequestreview-730285752).
Please give me your opinion if there is anything else to fix besides feedback.

**Comment by aiclaudev** [comment]
## Euphony-Speaker demo app
***
**Euphony Speaker demo app** generates noiseless sound wave to send the data.
When transferring data, the 'Speaker' generates an inaudible frequency and the 'Listener' receives it.
Follow the steps below and experience sound communication.


## Getting Started
***
#### 1. Open Android Studio
Clone the project and open it with Android Studio.

#### 2. Run the app
Select an Android emulator or device and run the app.

<img width="40%" alt="screenshot" src="https://user-images.githubusercontent.com/8490058/129358218-e53e4edd-dfe4-4930-bf82-1ed61bdc5b6b.jpg"></img>

You can enter the text you want to transmit. You can also select the number of transmissions in the spinner.  
You can send or stop sending text via the button at the bottom.

A guidance screencast is available [here](https://www.youtube.com/watch?v=eeg3ShVhSXs).

💡 Recommendation! You can try it with [Euphony-Listener demo app](https://github.com/euphony-io/euphony-listener).


## Compatibility
***
Minimum Android SDK: Euphony requires at least Android API 14.


## License
***
Euphony-speaker is licensed under the Apache 2.0 license. See the [LICENSE](https://github.com/euphony-io/euphony-speaker/blob/master/LICENSE) file for details.


## Report Issues
***
To report a specific problem or feature request, [please open a new issue](https://github.com/euphony-io/euphony-speaker/issues/new).


## Library
***
![euphony_logo](https://user-images.githubusercontent.com/8490058/129358383-14b6f34d-9264-4c49-9538-3ef2e62a6490.png)

This demo-app is based on Euphony Library.

Euphony is Acoustic Data Telecommunication Library. This is for Android version.  
Euphony provides a handiness library designed to communicate with other devices(android and web) using mic and recorder.

Official Facebook Page : https://www.facebook.com/euphonyproject  
Official Library Site : https://dev.jbear.co/euphony

**Comment by aiclaudev** [comment]
I modified the README file by reflecting the mentor's feedback. 
Tell me if there's anything missing or if there's anything else that needs to fix.

**Comment by jopopcorn** [comment]
@aiclaudev You reflected it well according to the feedback!
Configuration is better than before.

Our mentor said that we need a self-review.
Please upload the modified README configuration and self-review through the link below!
https://github.com/euphony-io/euphony-speaker/pull/6#issuecomment-899209496
